apiVersion: v1
kind: Service
metadata:
  name: ctraffic-ipv4
spec:
  ipFamily: IPv4
  selector:
    app: ctraffic
  ports:
  - port: 5003
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ctraffic-ipv6
spec:
  ipFamily: IPv6
  selector:
    app: ctraffic
  ports:
  - port: 5003
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ctraffic-deployment
spec:
  selector:
    matchLabels:
      app: ctraffic
  replicas: 4
  template:
    metadata:
      labels:
        app: ctraffic
    spec:
      containers:
      - name: ctraffic
        image: registry.nordix.org/cloud-native/ctraffic:latest
        ports:
        - containerPort: 5003
